Made URLs more RESTful.
vladvlad00/TBD-task-handler pull request #37
Opened 2021-05-15 16:28 UTC by Vlad-Enia

2021-05-16 16:07 UTC, robertadriang requested changes
Please reformat the code :')

2021-05-16 16:07 UTC, robertadriang commented on src/main/java/ro/uaic/info/taskhandler/controller/AnswerController.java
> +        } catch (Exception e)
try{
} catch {
} 
OR
try{
}
catch
{
}

2021-05-16 16:07 UTC, robertadriang commented on src/main/java/ro/uaic/info/taskhandler/controller/AnswerController.java
> +        } catch (Exception e)
try{
} catch {
}
OR
try{
}
catch
{
}

2021-05-16 16:07 UTC, robertadriang commented on src/main/java/ro/uaic/info/taskhandler/controller/ScoreAnswerController.java
> +        } catch (Exception e)
try{
} catch {
}
OR
try{
}
catch
{
}

2021-05-16 16:07 UTC, robertadriang commented on src/main/java/ro/uaic/info/taskhandler/controller/ScoreAnswerController.java
> +        } catch (Exception e)
try{
} catch {
}
OR
try{
}
catch
{
}

2021-05-16 16:07 UTC, robertadriang commented on src/main/java/ro/uaic/info/taskhandler/controller/TaskStudentController.java
> +        } else
}
else
}
OR
}else{

2021-05-17 17:50 UTC, vladvlad00 commented on src/main/java/ro/uaic/info/taskhandler/controller/ScoreAnswerController.java
> +        } catch (Exception e)
nu

2021-05-17 17:50 UTC, vladvlad00 approved these changes

2021-05-17 17:51 UTC, robertadriang approved these changes

2021-05-17 17:51 UTC, merged